### ISSUE TITLE
Set access when pinning

### ISSUE THREAD

**Issue by wyuill** [herts-phei/kingpin#19] opened 2022-11-30 10:55 UTC
May not be possible without changes to the pins package however there would be great value in being able to assign access whilst pinning (e.g. `pin_write(mtcars, access = "my_team")`) rather than having the user have to remember to set this on connect after pinning

**Comment by AYu1804** [comment] 2022-12-02 18:18
Duplicate of https://github.com/herts-phei/kingpin/issues/1

**Closed as completed** 2022-12-02 18:18 UTC
Labels: enhancement
